[package]
name    = "bon-macros"
version = "3.9.3"

description = """
This is a proc-macro crate that is supposed to be a private implementation
detail of the `bon` crate
"""

edition    = "2024"
homepage   = "https://bon-rs.com/"
license    = "MIT OR Apache-2.0"
repository = "https://github.com/elastio/bon"

# This MSRV is dictated by our dependency on darling@0.24, which is the first
# version that uses syn@3.0.
rust-version = "1.88.0"

[package.metadata.docs.rs]
all-features = true

# Generate clickable links in the source code view in the docs
rustdoc-args = ["--generate-link-to-definition"]

# We don't need the docs to be built for every first-tier target.
# This crate is not platform-specific.
targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
# Darling `0.24` is the first version that uses `syn` `3.0`, which we require.
# The `.1` patch contains an import fix for this issue:
# https://github.com/TedDriggs/darling/issues/433
darling = ">=0.24.1, <0.25.0"

# This dependency is used by `darling` itself, so we use it as well for case
# conversions to share the same dependency.
ident_case = "1"

# This version still supports our MSRV and it is where this bug was fixed:
# https://github.com/dtolnay/proc-macro2/issues/470
proc-macro2 = "1.0.88"

quote = "1"

syn = { version = "3.0.3", features = ["full", "visit-mut", "visit"] }

prettyplease = "0.3"

[features]
default = []

alloc = []
std   = []

# See the docs on this feature in the `bon`'s crate `Cargo.toml`
experimental-overwritable = []

# See the docs on this feature in the `bon`'s crate `Cargo.toml`
experimental-generics-setters = []

# See the docs on this feature in the `bon`'s crate `Cargo.toml`
implied-bounds = []

[dev-dependencies]
expect-test = "1.4.1"
