// This is extremely perplexing, but by wrapping the struct in a macro, the lints
// such as `private_bounds` or `clippy::missing_const_for_fn` are triggered if
// code generated by `bon` violates it. Without it no lint is triggered.
macro_rules! test {
    () => {
        #[::bon::builder]
        pub struct WrappedByMacroRules {
            _field: u32,
        }
    };
}

test!();
